### ISSUE TITLE
Limit removing properties to certain JSX objects

### ISSUE THREAD

**Issue by sateffen** [oliviertassinari/babel-plugin-react-remove-properties#15]
Hey,

it would be great to have an option to limit removing some properties only from certain JSX elements, like removing `data-test` only from `<div>` elements, but not from `<span>` elements (yes, this example makes no sense, in our usecase it makes more sense).

**Comment by oliviertassinari** [comment]
Sounds fair. We could add a whitelist or a blacklist option. Do you want to give it a try? Sounds straitghtforward to implement.

**Comment by sateffen** [comment]
Usually I implement it myself, because it is indeed quite simple, but I'm totally out of time, and there are some other things that have a higher priority currently. That's the (sad) reason there is no PR for this issue.

**Comment by oliviertassinari** [comment]
I'm closing the issue. There is no point at keeping it open.
