### ISSUE TITLE
cannot get this to work

### ISSUE THREAD

**Issue by qhenkart** [oliviertassinari/babel-plugin-react-remove-properties#5]
.babelrc
```javascript
{
  "env": {
    "production": {
      "plugins": ["react-remove-properties"]
    } 
  },
  "presets": ["react", "es2015", "stage-2"]
}
```

code:
```javascript
render: function(){
      console.log(process.env.NODE_ENV, process.env.BABEL_ENV)
      return (
        <div className="canvas" data-test="quest">
```

Those console.logs confirm that both the default Babel_env and Node_env are set to production. I am setting the environment via webpack

I realize I don't need to set them both
```javascript
plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"',
      'process.env.BABEL_ENV': '"production"'
    })
  ]
```

No matter what I do or how I mess with the configuration. data-test="quest" never gets removed 

running Babel v6.4.0

**Comment by oliviertassinari** [comment]
I guess you are using the `0.2.0` release. I'm wondering if the ordre in which the presets and plugin are defined has any impact. I mean, would this work?
```json
{
  "presets": ["react", "es2015", "stage-2"], 
  "env": {
    "production": {
      "plugins": ["react-remove-properties"]
    } 
  }
} 
```
(that's just a guess).

**Comment by qhenkart** [comment]
I guessed the same and actually had originally tried it in that way. Is there another version you would recommend? I'll try to debug it and let you know what I find

**Comment by oliviertassinari** [comment]
The other release don't support babel6. So we are out of luck.
Yeah, I would love to know why this is not working for you. The test is green and that was working on my project, I think that it's still true.
The source code is really simple, good luck :grin:.

**Comment by oliviertassinari** [comment]
I'm closing this issue. I haven't had any issue on my side.

**Comment by ewu02** [comment]
@qhenkart I encountered the same issue using similar versions. I resolved it by defining the environment at the cli; e.g., `NODE_ENV=production webpack`. It seems .babelrc's env-specific plugins is determined before the environment is set by webpack.DefinePlugin, or not affected at all. Without NODE_ENV or BABEL_ENV defined beforehand, .babelrc defaults to development env settings.

**Comment by oliviertassinari** [comment]
@ewu02 Yes, the behavior you are describing is expected.
